version: '2'
services:
  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    restart: always
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /mnt/docker/portainer:/data
